### PR TITLE
A lot of bugfixes, corrected iterator changes from #5, lowered memory overhead per object

### PR DESCRIPTION
**Pull request by solamyl**
* #10 - bugfix in push_front()
* #11 - bugfix in index() calculation from negative pos
* #12 - bugfix in copy constructor and operator=()
* #13 - bugfix in insert()
* #14 - bugfix in resolve_overflow()
* #15 - corrected work with iterators that started in #5 and #6
* #16 - saved memory overhead per object (10 => 4 bytes on Arduino Nano)
* some minor improvements

### CODE REVIEW

**Comment by solamyl** [comment]
I have forgot to mention, that this time I have tested all changes on all examples :-)

**Review by hideakitai — APPROVED** [review]
LGTM! Thank you so much!

**Comment by solamyl** [comment]
Recently, I have started to use simplier array container than arx::, but I like the idea and design of RingBuffer that I use in some projects :-)

**Comment by hideakitai** [comment]
I really appreciate your contribution! ;-)

**Pull request merged**
